# Generated by Django 6.1.1 on 2026-09-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_tag_product_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="myapp.tag"
            ),
        ),
    ]
