# Generated by Django 6.1.1 on 2026-09-30 09:57

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_product_tag"),
    ]

    operations = [
        TrigramExtension(),
    ]
