# Generated by Django 6.1.1 on 2026-09-30 11:05

from django.db import migrations
from django.contrib.postgres.search import SearchVector

def populate_search_vector(apps, schema_editor):
    Product = apps.get_model('myapp', 'Product')
    Product.objects.update(
        search_vector=SearchVector('title', weight='A') + SearchVector('description', weight='B')
    )

def reverse_populate(apps, schema_editor):
    Product = apps.get_model('myapp', 'Product')
    Product.objects.update(search_vector=None)

class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_product_search_vector_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_search_vector, reverse_populate),
    ]
