# Generated by Django 6.1.1 on 2026-10-02 15:34

from django.db import migrations

def create_uncategorized_category(apps, schema_editor):
    Category = apps.get_model('myapp', 'Category')
    Product = apps.get_model('myapp', 'Product')

    uncategorized, _ = Category.objects.get_or_create(
        slug='uncategorized',
        defaults={'name': 'Uncategorized'},
    )

    orphaned_products = Product.objects.filter(category__isnull=True)
    if orphaned_products.exists():
        Product.category.through.objects.bulk_create([
            Product.category.through(product_id=prod.pk, category_id=uncategorized.pk)
            for prod in orphaned_products
        ])

def remove_uncategorized_category(apps, schema_editor):
    Category = apps.get_model('myapp', 'Category')
    try:
        uncategorized = Category.objects.get(slug='uncategorized')
        uncategorized.products.clear()
        uncategorized.delete()
    except Category.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_category_product_category"),
    ]

    operations = [
        migrations.RunPython(
            create_uncategorized_category,
            remove_uncategorized_category
        )
    ]
