# Generated by Django 6.1.1 on 2026-10-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_create_uncategorized_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Category",
            new_name="category",
        ),
    ]
