# Generated by Django 6.1.1 on 2026-10-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_feature_featurevalue_productfeature"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featurevalue",
            options={"ordering": ["feature__display_order", "display_order", "value"]},
        ),
        migrations.AlterUniqueTogether(
            name="featurevalue",
            unique_together={("feature", "value")},
        ),
    ]
