# Generated by Django 6.1.1 on 2026-10-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_featurevalue_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="featurevalue",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="featurevalue",
            name="numeric_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional; the value expressed in the feature's base unit",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="featurevalue",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="Display unit e.g. TB, GB, MB, or leave blank for not-measured",
                max_length=25,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featurevalue",
            unique_together={("feature", "value", "unit")},
        ),
    ]
