# Generated by Django 6.1.1 on 2026-10-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_featurevalue_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="unit",
        ),
        migrations.AddField(
            model_name="feature",
            name="base_unit",
            field=models.CharField(
                blank=True, help_text="Canonical unit for numeric_value", max_length=25
            ),
        ),
    ]
