# Generated by Django 6.1.1 on 2026-09-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_product_tag"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="wishlist_items",
            new_name="WishlistItems",
        ),
    ]
